[package]
name = "simd-vol"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wide = "0.7.13"
implied-vol = "0.2"
bytemuck = "1.14.1"
rayon = "1.8.1"
